CREATE DATABASE IF NOT EXISTS jewellery
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE jewellery;

CREATE TABLE IF NOT EXISTS site_data (
  id VARCHAR(32) NOT NULL PRIMARY KEY,
  payload LONGTEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS products (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  sort_order INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  sku VARCHAR(255) NOT NULL UNIQUE,
  category VARCHAR(255) NOT NULL,
  collection VARCHAR(255) NOT NULL,
  material VARCHAR(255) NOT NULL,
  purity VARCHAR(255) NOT NULL,
  occasion VARCHAR(255) NOT NULL,
  price DECIMAL(12,2) NOT NULL,
  mrp DECIMAL(12,2) NOT NULL,
  rating DECIMAL(4,2) NOT NULL,
  image LONGTEXT NOT NULL,
  images JSON NOT NULL,
  description LONGTEXT NOT NULL,
  weight VARCHAR(255) NOT NULL,
  stone VARCHAR(255) NOT NULL,
  badge VARCHAR(255) DEFAULT NULL,
  stock INT NOT NULL,
  low_stock_limit INT NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  featured TINYINT(1) NOT NULL DEFAULT 0,
  bestseller TINYINT(1) NOT NULL DEFAULT 0,
  new_arrival TINYINT(1) NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS categories (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  sort_order INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  image LONGTEXT NOT NULL,
  description LONGTEXT NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS collections (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  sort_order INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  image LONGTEXT NOT NULL,
  description LONGTEXT NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  featured TINYINT(1) NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS enquiries (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  sort_order INT NOT NULL,
  customer_name VARCHAR(255) NOT NULL,
  phone VARCHAR(64) NOT NULL,
  email VARCHAR(255) NOT NULL,
  requirement VARCHAR(255) NOT NULL,
  budget VARCHAR(64) NOT NULL,
  message LONGTEXT NOT NULL,
  enquiry_date DATE NOT NULL,
  status VARCHAR(32) NOT NULL,
  admin_notes LONGTEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS offers (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  sort_order INT NOT NULL,
  offer_name VARCHAR(255) NOT NULL,
  coupon_code VARCHAR(255) NOT NULL,
  discount_percentage INT NOT NULL,
  start_date DATE NOT NULL,
  expiry_date DATE NOT NULL,
  apply_to VARCHAR(32) NOT NULL,
  selection_ids JSON NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS homepage (
  id VARCHAR(32) NOT NULL PRIMARY KEY,
  hero_banners JSON NOT NULL,
  featured_product_ids JSON NOT NULL,
  new_arrival_ids JSON NOT NULL,
  bestseller_ids JSON NOT NULL,
  featured_category_ids JSON NOT NULL,
  promotional_banners JSON NOT NULL,
  section_visibility JSON NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS settings (
  id VARCHAR(32) NOT NULL PRIMARY KEY,
  website_logo VARCHAR(255) NOT NULL,
  business_name VARCHAR(255) NOT NULL,
  phone_number VARCHAR(64) NOT NULL,
  whatsapp_number VARCHAR(64) NOT NULL,
  email VARCHAR(255) NOT NULL,
  address LONGTEXT NOT NULL,
  facebook_url LONGTEXT NOT NULL,
  instagram_url LONGTEXT NOT NULL,
  youtube_url LONGTEXT NOT NULL,
  other_links LONGTEXT NOT NULL,
  business_information LONGTEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stock_history (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  sort_order INT NOT NULL,
  product_id VARCHAR(64) NOT NULL,
  entry_date DATETIME NOT NULL,
  previous_stock INT NOT NULL,
  quantity_changed INT NOT NULL,
  updated_stock INT NOT NULL,
  reason LONGTEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS admin_users (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  sort_order INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(64) NOT NULL,
  remember TINYINT(1) NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_admin_email (email)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
